# main package
[project]
name = "foo"
version = "1.1"
dependencies = [
    "foo-default-extras<=1.1",
]

[project.optional-dependencies]
extra-a = ["dep-a"]
extra-b = ["dep-b"]
extra-c = ["dep-c"]
no-default-extras = ["foo-default-extras==0"]
